# Generated by Django 4.2.5 on 2024-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pagestate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestate',
            name='profile',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
