# Generated by Django 4.2.5 on 2024-03-04 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='observed_by', to=settings.AUTH_USER_MODEL)),
                ('observer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='observer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
